app:
  name: isspay
  env: dev
db:
  host: db
  port: 5432
  user: dev
  password: dev
  dbname: isspay_dev
  type: postgres
log:
  env: dev
  type: zap
  app_name: isspay
  level: debug
http_server:
  host: 0.0.0.0
  port: 8080